/**
 * Module: config.ts
 * Configuration utility module
 *
 * Description:
 * - Provides config file read/write functionality
 * - Manages environment variables and config files
 * - Validates and normalizes Affine server URLs
 * - Loads full config and provides default workspace ID
 *
 * Config loading priority: env vars > local .env > global ~/.affine-cli/affine-cli.env
 *
 * Exported config items:
 * - AFFINE_BASE_URL: Affine server URL (default https://app.affine.pro)
 * - AFFINE_API_TOKEN: Auth credentials
 * - AFFINE_WORKSPACE_ID: Default workspace ID
 */

import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

/**
 * GLOBAL_CONFIG_DIR: Global config directory
 * Path: ~/.affine-cli/
 */
export const GLOBAL_CONFIG_DIR = path.join(os.homedir(), '.affine-cli');

/**
 * GLOBAL_CONFIG_FILE: Global config file path
 * Path: ~/.affine-cli/affine-cli.env
 */
export const GLOBAL_CONFIG_FILE = path.join(GLOBAL_CONFIG_DIR, 'affine-cli.env');

/**
 * LOCAL_CONFIG_FILE: Local config file path
 * Path: <current working directory>/.env
 */
export const LOCAL_CONFIG_FILE = path.join(process.cwd(), '.env');

/**
 * readKeyValueFile: Read key=value format config file
 *
 * @param filePath - Config file path
 * @returns Config key-value object, empty object if file does not exist
 *
 * Notes:
 * - Skip empty lines and lines starting with #
 * - Use = as key-value separator
 */
export function readKeyValueFile(filePath: string): Record<string, string> {
	if (!fs.existsSync(filePath)) return {};
	const content = fs.readFileSync(filePath, 'utf-8');
	const result: Record<string, string> = {};
	for (const line of content.split('\n')) {
		const trimmed = line.trim();
		if (!trimmed || trimmed.startsWith('#')) continue;
		const eq = trimmed.indexOf('=');
		if (eq === -1) continue;
		result[trimmed.slice(0, eq)] = trimmed.slice(eq + 1);
	}
	return result;
}

/**
 * loadConfigFile: Load merged config file results
 *
 * @returns Merged config key-value object
 *
 * Config priority (high to low):
 * - Environment variables (process.env)
 * - Local .env (LOCAL_CONFIG_FILE)
 * - Global config file (GLOBAL_CONFIG_FILE)
 */
export function loadConfigFile(): Record<string, string> {
	const globalConfig = readKeyValueFile(GLOBAL_CONFIG_FILE);
	const localConfig = readKeyValueFile(LOCAL_CONFIG_FILE);
	const merged: Record<string, string> = { ...globalConfig };
	for (const [key, value] of Object.entries(localConfig)) {
		if (value) merged[key] = value;
	}
	return merged;
}

/**
 * writeConfigFile: Write config file
 *
 * @param vars - Config key-value pairs
 * @param useLocal - Whether to write local config file, default false writes to global config
 *
 * Notes:
 * - Global config write uses atomic operation (write temp file then rename)
 * - Local config writes directly to .env in current directory
 */
export function writeConfigFile(vars: Record<string, string>, useLocal: boolean = false) {
	const configDir = useLocal ? process.cwd() : GLOBAL_CONFIG_DIR;
	const configFile = useLocal ? LOCAL_CONFIG_FILE : GLOBAL_CONFIG_FILE;

	const lines = [
		'# Affine CLI credentials',
		'# Generated by: affine-cli login',
		`# ${new Date().toISOString()}`
	];
	for (const [key, value] of Object.entries(vars)) {
		if (value) lines.push(`${key}=${value}`);
	}
	lines.push('');

	if (useLocal) {
		fs.writeFileSync(configFile, lines.join('\n'));
		return;
	}

	const tmpFile = path.join(configDir, `.config.tmp.${process.pid}`);
	try {
		fs.mkdirSync(configDir, { recursive: true, mode: 0o700 });
		fs.writeFileSync(tmpFile, lines.join('\n'), { mode: 0o600 });
		fs.renameSync(tmpFile, GLOBAL_CONFIG_FILE);
	} catch (err) {
		try {
			fs.unlinkSync(tmpFile);
		} catch {}
		throw err;
	}
}

/**
 * validateBaseUrl: Validate and normalize URL
 *
 * @param input - Input URL string
 * @returns Normalized URL (trailing slash removed)
 * @throws If URL is invalid or protocol is unsupported
 *
 * Notes:
 * - Embedded credentials not supported (user:pass@host)
 * - Only http/https protocols supported
 * - Non-local HTTP URLs produce a warning
 */
export function validateBaseUrl(input: string): string {
	let parsed: URL;
	try {
		parsed = new URL(input);
	} catch {
		throw new Error(`Invalid URL: ${input}`);
	}
	if (parsed.username || parsed.password) {
		throw new Error('URL cannot contain embedded credentials (user:pass@host)');
	}
	if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
		throw new Error(`Unsupported URL protocol: ${parsed.protocol} (only http/https supported)`);
	}
	const host = parsed.hostname;
	const isLocal =
		host === 'localhost' || host === '127.0.0.1' || host === '::1' || host === '0.0.0.0';
	if (parsed.protocol === 'http:' && !isLocal) {
		console.error('Warning: Using non-local HTTP URL, HTTPS recommended');
	}
	return parsed.origin + parsed.pathname.replace(/\/$/, '');
}

/**
 * env: Get effective config value
 *
 * @param name - Environment variable name
 * @param file - Config file object
 * @param fallback - Fallback value
 * @returns Config value
 *
 * Priority (high to low): env vars > config file > fallback
 */
function env(name: string, file: Record<string, string>, fallback?: string): string | undefined {
	return process.env[name] || file[name] || fallback;
}

let cachedConfig: { baseUrl: string; apiToken?: string; defaultWorkspaceId?: string } | null = null;

export function clearConfigCache() {
	cachedConfig = null;
}

/**
 * loadConfig: Load full config
 *
 * @returns Config object with baseUrl, apiToken, cookie, defaultWorkspaceId
 *
 * Notes:
 * - AFFINE_BASE_URL defaults to https://app.affine.pro
 * - Other config items have no default, read from env vars or config file
 */
export function loadConfig() {
	if (cachedConfig) return cachedConfig;

	const file = loadConfigFile();
	const baseUrl = validateBaseUrl(env('AFFINE_BASE_URL', file, 'https://app.affine.pro')!);
	const apiToken = env('AFFINE_API_TOKEN', file);
	const defaultWorkspaceId = env('AFFINE_WORKSPACE_ID', file);

	cachedConfig = {
		baseUrl,
		apiToken,
		defaultWorkspaceId
	};
	return cachedConfig;
}

/**
 * redactSecret: Redact secret for display
 *
 * @param value - Raw secret
 * @returns Redacted value
 *
 * Usage examples:
 * - "abc123" → "****3"
 * - "longer-secret-key" → "abcd…ey"
 */
export function redactSecret(value: string | undefined): string | null {
	if (!value) return null;
	if (value.length <= 8) return '*'.repeat(value.length);
	return `${value.slice(0, 4)}…${value.slice(-4)}`;
}

/**
 * getWorkspaceId: Get workspace ID
 *
 * @param paramsWorkspaceId - Optional workspace ID parameter
 * @returns Workspace ID
 * @throws If workspace ID not specified and not set in config
 *
 * Priority (high to low):
 * - Parameter paramsWorkspaceId
 * - Config AFFINE_WORKSPACE_ID
 *
 * Usage examples:
 * - getWorkspaceId() // Use default workspace from config
 * - getWorkspaceId('workspace-123') // Use workspace specified by parameter
 */
/**
 * Get Affine base URL
 *
 * @returns Base URL (default https://app.affine.pro)
 */
export function getBaseUrl(): string {
	const config = loadConfig();
	return config.baseUrl;
}

/**
 * Get workspace ID
 *
 * Priority: parameter > env vars/config > error
 *
 * Accepts either a UUID or a workspace name; names are resolved via the
 * on-disk cache (refreshed automatically on miss).
 *
 * @param paramsWorkspaceId - Optional workspace ID or name
 * @returns Workspace UUID
 * @throws If workspaceId is not configured, or if a name cannot be resolved
 */
export async function getWorkspaceId(paramsWorkspaceId?: string): Promise<string> {
	const config = loadConfig();
	const input = paramsWorkspaceId || config.defaultWorkspaceId;
	if (!input) {
		throw new Error(
			'Workspace ID not specified. Use --workspace parameter or set AFFINE_WORKSPACE_ID in config'
		);
	}
	// Lazy-import to avoid a cycle: workspaceCache imports from wsClient,
	// which has no dependency on config.
	const { resolveWorkspaceIdOrName } = await import('./workspaceCache.js');
	return resolveWorkspaceIdOrName(input);
}

/**
 * Get API config
 *
 * @param paramsWorkspaceId - Optional workspace ID parameter
 * @returns API config object with apiUrl, apiToken, workspaceId
 */
export function getApiConfig() {
	const config = loadConfig();

	return {
		apiUrl: `${config.baseUrl}/graphql`,
		apiToken: config.apiToken
	};
}
